[project]
name = "agentconversationretrievalsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.9.1",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
]
